
# # sticky floor
# PerceptionRadius = 1.0
# SeparationWeight = 200.0
# AlignmentWeight = 1.0
# CohesionWeight = 10.0
# DeltaSeconds = 0.1
# RandomnessDeviation = 0.000000001
# ViewSize = 40.0
# ShapeRadius = 0.4
# OnKeyVelocityChange = 1.0

# # squeezing through the mosh pit
# PerceptionRadius = 6.0
# SeparationWeight = 120.0
# AlignmentWeight = 1.0
# CohesionWeight = 10.0
# DeltaSeconds = 0.1
# RandomnessDeviation = 0.1
# ViewSize = 40.0
# ShapeRadius = 0.4
# OnKeyVelocityChange = 1.0

# # ???
PerceptionRadius = 100.0
SeparationWeight = 1.0
AlignmentWeight = 100.0
CohesionWeight = 1.0
DeltaSeconds = 0.1
RandomnessDeviation = 0.001
ViewSize = 5.0
ShapeRadius = 0.04
OnKeyVelocityChange = 0.1

Boids = [
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
    { pos = [0.0, 0.0, 0.0], vel = [0.0, 0.0, 0.0] },
]
