[package]
name = "intersection-4-way"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wiringpi = "0.2.4"
#wiringpi = { features = "0.2.4", features = ["development"] }

