[package]
name = "message-io-chat-server"
version = "0.1.0"
authors = ["Damian Grüner (Dreamykass) <grunerdamian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message-io = "0.14.2"
