[package]
name = "ecs"
version = "0.1.0"
authors = ["Damian Grüner <grunerdamian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.3.1"
