[package]
name = "exploration"
version = "0.1.0"
authors = ["Damian Grüner <grunerdamian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24.0"
futures = "0.3"
wgpu-subscriber = "0.1.0"
#shaderc = "0.7"
inline-spirv = "0.1.2"

[dependencies.wgpu]
version = "0.6"
features = ["vulkan-portability"]